Design patterns p4
BorysovskaOA/SW_Design-Algorithms pull request #8
Opened 2020-11-22 11:54 UTC by BorysovskaOA

2020-12-07 06:56 UTC, AlexHladin requested changes

2020-12-07 06:56 UTC, AlexHladin commented on design_patterns/src/shipments/ShipmentInterface.ts
> +export interface ShipmentInterface {
@BorysovskaOA, this interface volatiles the interface segregation principle. The `ship` method should be extracted into a separated interface.

2020-12-07 06:56 UTC, AlexHladin commented on design_patterns/src/shipments/ShipmentMarksDecorator.ts
> +  public ship() {
@BorysovskaOA, decorate ship method only.

2020-12-08 12:16 UTC, BorysovskaOA commented on design_patterns/src/shipments/ShipmentInterface.ts
> +export interface ShipmentInterface {
Created Shippable interface.

2020-12-08 12:16 UTC, BorysovskaOA commented on design_patterns/src/shipments/ShipmentMarksDecorator.ts
> +  public ship() {
Removed extra methods from decorator.

2020-12-08 12:22 UTC, AlexHladin approved these changes

2020-12-09 10:35 UTC, merged